seo:
  keywords: nutriolab, nutribless, indonesia, teknologi pangan, makanan, minuman, konsultan pangan, UMKM, bisnis makanan minuman, teknologi pangan, konsultasi online, bisnis kecil, nutrisi, bisnis kuliner, kuliner, jualan online
  description: Kami bukan sekedar konsultan pangan, Kami adalah perpanjangan dari tim Anda, Bersama-sama kita bangun masa depan industri pangan.
  image_url: /assets/media/seo.png
