seo:
  keywords: nutriolab, nutribless, food science, food safety, food engineering, consultant, sensory, indonesia, enterprises, SME, food consultant, start up, affordable, food packaging, quality, nutrition
  description: We are not just a food consultant. We are the extension of your team. Together we build the future of food industry.
  image_url: /assets/media/seo.png