- name: Package A - General Food Science
  options:
    - title: 101
      name: Basic
      description: Q&A covering basic food science and general food product development.
      services:
        - ++ Consultation (50 min)
      price:
        value: '750'
        cardinal: k
    - title: 102
      name: Standard
      description: Standard consultation covering food science, general food product development/innovation.
      services:
        - ++ Consultation (50 min)
        - ++ Report Delivery
      price:
        value: '1,25'
        cardinal: mio
    - title: 103
      name: Premium
      description: In-depth consultation in food science, daily findings with no specific topic, tips and trick, ideation, general product development/innovation brainstorm, product values & uniqueness
      services:
        - ++ Consultation (50 min)
        - ++ Report Delivery
        - ++ Testing / Analysis
- name: Package B - Food Processing
  options:
    - title: 101
      name: Basic
      description: Q&A covering basic application of food engineering, including process selection, process parameters and basic production flow.
      services:
        - ++ Consultation (50 min)
      price:
        value: '1,5'
        cardinal: mio
    - title: 102
      name: Standard
      description: Standard consultation covering basic application of food engineering, including process selection, process parameters and basic production flow - food safety focus.
      services:
        - ++ Consultation (50 min)
        - ++ Report Delivery
      price:
        value: '2,0'
        cardinal: mio
    - title: 103
      name: Premium
      description: |
        In-depth consultation related to 
        (1) Home scale production: processing parameters, equipment, quality/ safety, 
        (2) Mid-pilot scale production: processing parameters, equipment, quality/safety, 
        (3) Management production  (PPIC, scheduling, scaling up, production flow), hygienic design - food safety focus. 
      services:
        - ++ Consultation (50 min)
        - ++ Report Delivery
        - ++ Testing / Analysis
- name: Package C - Food Packaging
  options:
    - title: 101
      name: Basic
      description: Q&A covering basic insight of food packaging selection and food shelf-life.
      services:
        - ++ Consultation (50 min)
      price:
        value: '1'
        cardinal: mio
    - title: 102
      name: Standard
      description: Standard consultation covering food packaging selection, food shelf-life determination, and food labeling.
      services:
        - ++ Consultation (50 min)
        - ++ Report Delivery
      price:
        value: '1,5'
        cardinal: mio
    - title: 103
      name: Premium
      description: |
        In-depth analysis related to 
        (1) Packaging selection, food packaging interaction, package assessment, 
        (2) Appropriate generic claims & labelling - food regulation and standard  (PIRT, BPOM, Halal), 
        (3) Product shelf-life limitation. how to predict shelf life (testing, estimation, literature review, mini trial), prolong product shelf life. 
      services:
        - ++ Consultation (50 min)
        - ++ Report Delivery
        - ++ Testing / Analysis
- name: Package D - Nutrition
  options:
    - title: 101
      name: Basic
      description: Q&A covering basic analysis of product value like nutrition and health benefit.
      services:
        - ++ Consultation (50 min)
      price:
        value: '1'
        cardinal: mio
    - title: 102
      name: Standard
      description: Standard consultation covering analysis of product value (nutrition, health benefits, functionality).
      services:
        - ++ Consultation (50 min)
        - ++ Report Delivery
      price:
        value: '1,5'
        cardinal: mio
    - title: 103
      name: Premium
      description: |
        In-depth analysis of product value (nutrition, health benefits, functionality), appropriate nutrition/health claims & nutrition-facts label
      services:
        - ++ Consultation (50 min)
        - ++ Report Delivery
        - ++ Testing / Analysis
- name: Package E - Consumer Study
  options:
    - title: 101
      name: Basic
      description: Q&A covering basic sensory evaluation design.
      services:
        - ++ Consultation (50 min)
      price:
        value: '1'
        cardinal: mio
    - title: 102
      name: Standard
      description: Standard consultation covering sensory evaluation design and customer feedback, and basic product positioning.
      services:
        - ++ Consultation (50 min)
        - ++ Report Delivery
      price:
        value: '1,5'
        cardinal: mio
    - title: 103
      name: Premium
      description: |
        In-depth analysis covering 
        (1) Sensory evaluation design and customer feedback, 
        (2) Product positioning, competitiveness, branding (business development), 
        (3) Finance and cost analysis - how to define product value and business development.
      services:
        - ++ Consultation (50 min)
        - ++ Report Delivery
        - ++ Testing / Analysis
---
